34 the app implement folder structure
Aktion-Sodis/software-main pull request #35
Opened 2022-02-07 16:39 UTC by BeneSchier

Set up Folder Structure with consideration of Blocs and Model conversion etc. 

#34 

https://github.com/Aktion-Sodis/software-main/issues/34

2022-02-09 01:08 UTC, arthur-becker requested changes
At the moment, I would let the folder "Blocs" be empty, because blocs in this folder have more to do with the structure of the frontend than with the structure of models in the database

2022-02-12 18:43 UTC, BeneSchier commented
I changed the Blocs Folder, now it's empty

2022-02-22 12:06 UTC, arthur-becker approved these changes

2022-02-26 20:44 UTC, CoachBenedetto approved these changes
folder structure approved

2022-02-26 20:46 UTC, merged