63/api---add-multi-language-support-to-backend
Aktion-Sodis/software-main pull request #67
Opened 2022-03-09 20:13 UTC by CoachBenedetto

Fixing issue 63

2022-03-09 20:14 UTC, CoachBenedetto commented
@apolat2000 please review :D

2022-03-10 06:24 UTC, apolat2000 requested changes
@CoachBenedetto I left some comments. They should be covered before approval.

2022-03-10 06:24 UTC, apolat2000 commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
> +type MultiLanguageText {
@CoachBenedetto Can you please name this `i18nString` bcuz "i18n" for the consistency of the notions we use and "String" because it is literally a string object?

2022-03-10 06:24 UTC, apolat2000 commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
> +}
(I duplicated my comment from above) @CoachBenedetto why are we making these changes in this PR? Please either generalize the issue #63, or create new PRs for each logical unit. The prior saves time and latter is good practice, choose your way :)

2022-03-10 06:24 UTC, apolat2000 commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
> -
@CoachBenedetto why are we making these changes in this PR? Please either generalize the issue #63, or create new PRs for each logical unit. The prior saves time and latter is good practice, choose your way :)

2022-03-10 06:29 UTC, CoachBenedetto commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
> +type MultiLanguageText {
Can you please say those things before me making backend changes in future. This means 30-60 minutes completely unnecessary time from my side. We had discussed this yesterday.

2022-03-10 07:37 UTC, CoachBenedetto commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
> +type MultiLanguageText {
Is Added. But the I had to be an upper case due to naming restrictions of amplify

2022-03-10 07:55 UTC, apolat2000 requested changes
@CoachBenedetto I've found that Entity name is still String. Was it on purpose? Of course it could make sense, but e.g. a place can be called differently in different languages, e.g. Aquisgrana and Aachen. I think it is safer now to localize it now then later when it might be too much work.

Also, don't you think AppliedCustomData, Marking, Task and Tags should also be localized?

2022-03-10 07:55 UTC, apolat2000 commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
>    name: String!
@CoachBenedetto Missing

2022-03-10 08:52 UTC, CoachBenedetto commented on admin-app/frontend/amplify/backend/api/monitoring/schema.graphql
>    name: String!
have added in schema only @apolat2000

2022-03-10 09:10 UTC, apolat2000 submitted a review, later dismissed
LGTM

2022-03-10 13:15 UTC, CoachBenedetto commented
Backend updated. Now approve ready :D @apolat2000

2022-03-10 13:18 UTC, apolat2000 approved these changes
Thank you Benedikt

2022-03-10 13:20 UTC, merged